/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "reg.h"

	/*uint32_t volatile *pClkCtrlreg = (uint32_t*)0x40023830;
	uint32_t volatile *pPortAModereg = (uint32_t*)0x40020000;
	uint32_t volatile *pPortAOutreg = (uint32_t*)0x40020014;
	uint32_t volatile *pPortAInreg = (uint32_t*)0x40020010;
	uint32_t volatile *pPortAPupdr = (uint32_t*)0x4002000C;*/

int main(void)
{

	RCC_AHB1ENR volatile 	*const pClkCtrlreg 	= 	(RCC_AHB1ENR*) 		0x40023830;
	GPIOx_MODE volatile 	*const pPortAModereg = 	(GPIOx_MODE*)		0x40020000;
	GPIOx_ODR volatile 		*const pPortAOutreg = 	(GPIOx_ODR*)		0x40020014;
	GPIOx_IDR volatile 		*const pPortAInreg = 	(GPIOx_IDR*)		0x40020010;
	GPIOx_Pupdndr volatile 	*const pPortAPupdr = 	(GPIOx_Pupdndr*)	0x4002000C;



	//Enabling clock for GPIOA peripheral in AHBR1ENR
		pClkCtrlreg->gpioa_en = 1;

	//2. Configure the mode of the IO pin
		// a.Configuring Port 5 as Output
	 	pPortAModereg->pin_5 = 1;//Port 5 is output so 0 1

	 	 // b.Configuring Port 0 as Input
	 	pPortAModereg->pin_0 = 0;//Port 0 is input so 0 0

	//3. Configuring Pull-Down resistor
	 	pPortAPupdr->pin_0 = 2;

   while(1){


	   if(pPortAInreg->pin_0 == 1){
		   //3. Set the 5th bit of the output data register to make IO pin 5 to HIGH
		   pPortAOutreg->pin_5 = 1; //on
	   }else{

		   pPortAOutreg->pin_5 = 0; //off

	   }
   }


}

